// Generated by CoffeeScript 1.6.2
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  };

  exports.detail = function(req, res) {
    return res.render("detail");
  };

}).call(this);
