// Generated by CoffeeScript 1.6.2
(function() {
  var Linda, LindaClient, TupleSpace, linda;

  LindaClient = require("node-linda-client");

  Linda = LindaClient.Linda;

  TupleSpace = LindaClient.TupleSpace;

  linda = function(ts) {
    linda = new Linda("http://linda.masuilab.org");
    linda.ts = new TupleSpace(ts, linda);
    return linda;
    /*
    linda.io.on "connect", ->
      console.log "connect"
      linda.ts.watch [name], (tuple, info)->
        #console.log tuple, info
    */

  };

  module.exports = {
    linda: linda
  };

}).call(this);
